version: 2.1
jobs:
  build:
    docker:
      - image: golang:1.11
    working_directory: /go/src/github.com/glutamatt/webstun
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/v0.5.0/install.sh | sh
      - run: dep ensure --vendor-only
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -a -installsuffix nocgo -o build/webstun-linux-arm7 .
      - run: git describe --exact-match --tags $(git log -n1 --pretty='%h') > VERSION || echo "Not a tagged version"
      - persist_to_workspace:
          root: /go/src/github.com/glutamatt/webstun
          paths:
            - build
            - VERSION
  release:
    docker:
      - image: golang:1.11
    working_directory: /webstun
    steps:
      - attach_workspace:
          at: /webstun
      - run: go get -u github.com/tcnksm/ghr
      - run: ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete $(cat VERSION) ./build

  deploy:
    machine: true
    steps:
      - checkout
      - run: docker login --username=_ --password=${HEROKU_TOKEN} registry.heroku.com
      - run: docker build -t webstun .
      - run: docker tag webstun registry.heroku.com/${HEROKU_APP}/web
      - run: docker push registry.heroku.com/${HEROKU_APP}/web
      - run:
          name: deploy the last pushed image
          command: |
            WEB_DOCKER_IMAGE_ID=$(docker inspect registry.heroku.com/${HEROKU_APP}/web --format={{.Id}})
            curl --fail -X PATCH https://api.heroku.com/apps/${HEROKU_APP}/formation \
              -d '{"updates": [{"type": "web", "docker_image": "'"$WEB_DOCKER_IMAGE_ID"'"}]}' \
              -H "Content-Type: application/json" -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
              -H "Authorization: Bearer ${HEROKU_TOKEN}"

workflows:
  version: 2.1
  main:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - deploy
