version: 2.1
jobs:
  build:
    docker:
      - image: golang:1.11
    working_directory: /go/src/github.com/glutamatt/webstun
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/v0.5.0/install.sh | sh
      - run: dep ensure --vendor-only
      - run: |
        VERSION=$(git describe --exact-match --tags $(git log -n1 --pretty='%h'))
        echo $VERSION
        CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -a -installsuffix nocgo -ldflags "-X main.appVersion=$VERSION" -o build/webstun-linux-arm7 .
      - persist_to_workspace:
          root: /go/src/github.com/glutamatt/webstun
          paths:
            - build
  release:
    docker:
      - image: golang:1.11
    working_directory: /webstun
    steps:
      - attach_workspace:
          at: /webstun
      - run: go get -u github.com/tcnksm/ghr
      - run:
          name: create release
          command: |
            VERSION=$(./build/webstun-linux-arm7 -version)
            echo $VERSION
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./build

workflows:
  version: 2.1

  main:
    jobs:
      - build
      - release:
          requires:
            - build
  