version: 2.1
jobs:
  build:
    docker:
      - image: golang:1.11
    working_directory: /go/src/github.com/glutamatt/webstun
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/v0.5.0/install.sh | sh
      - run: dep ensure --vendor-only
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -a -installsuffix nocgo -o build/webstun-linux-arm7 .
      - persist_to_workspace:
          root: build
          paths:
            - webstun-linux-arm7
  release:
    docker:
      - image: golang:1.11
    steps:
      - attach_workspace:
        at: /build
      - run: go get -u github.com/tcnksm/ghr
      - run: go get -u github.com/stevenmatthewt/semantics
      - run:
          name: create release
          command: |
            tag=$(semantics --output-tag)
            if [ "$tag" ]; then
              ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace $tag /build
            else
              echo "The commit message(s) did not indicate a major/minor/patch version."
            fi

workflows:
  version: 2.1

  main:
    jobs:
      - build
      - release:
          requires:
            - build
